name: foxy

on:
  push:
    branches:
      - foxy
jobs:
  build_on_foxy_distro:
    runs-on: ubuntu-latest
    container:
      image: sntarg/unitree_ros:foxy
    steps:
      - name: Checkout Repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: . /opt/ros/foxy/setup.sh && colcon build
