name: humble

on: [push]
jobs:
  build_on_humble_distro:
    runs-on: ubuntu-latest
    container:
      image: sntarg/unitree_ros:humble
    steps:
      - name: Checkout Repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: . /opt/ros/humble/setup.sh && colcon build
