name: iron

on: [push]
jobs:
  build_on_iron_distro:
    runs-on: ubuntu-latest
    container:
      image: sntarg/unitree_ros:iron
    steps:
      - name: Checkout Repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: . /opt/ros/iron/setup.sh && colcon build
